# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/submitit/%j
timeout_min: 1440 # 24 hours, set to more if required
cpus_per_task: 32
gpus_per_node: null # Leave null
# If using ddp, this needs to be greater than or equal to the number of GPUs in each node
tasks_per_node: 1
mem_gb: 64
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: your_partition_here
qos: your_qos_here
comment: null
constraint: null # Leave null
exclude: null # Leave null
gres: "gpu:1" # The number of GPUs you require
cpus_per_gpu: null # Leave null
gpus_per_task: null # Leave null
mem_per_gpu: null # Leave null
mem_per_cpu: null # Leave null
account: your_account_here
max_num_timeout: 0
# Only include this if you want to requeue your jobs
additional_parameters: { signal: SIGUSR1@90, requeue: true }
# Idk what this does
array_parallelism: 10
# Put whatever commands you want to run before the job here
setup:
    - echo "Hello World"
    # To copy data with a progress bar
    # - rsync -ruP --stats /path/to/data/ /destination/path/on/node/